server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/cra_minidesk
    username: cra_user
    password: cra_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
